task: reg
dataset:
  path: data/house.csv           # 按需修改】你的数据路径
  target: price                  # 按需修改】目标列
  features: []                   # 留空=自动取数值列；含类别列时可留空自动OneHot
  test_size: 0.2
preprocess:
  dropna: false                  # 训练前是否丢弃缺失行（一般不丢，交给 Imputer 处理）
  impute_num: median
  impute_cat: most_frequent
  scale_num: true
  one_hot_cat: true
model:
  name: XGBoost
  params:
    n_estimators: 800
    max_depth: 8
    learning_rate: 0.05
    subsample: 0.9
    colsample_bytree: 0.9
    tree_method: hist
eval:
  metrics: [MAE, R2]             # 可选：覆盖默认
viz:
  enabled: true
  dpi: 160
  plots:
    feat_importance: true
    residuals: true
    pred_scatter: true
outputs:
  base_dir: outputs
  tag: house_xgb                 # 【可选修改】用于文件命名
seed: 42
