task: reg

dataset:
  path: outputs/data/artifacts/tabular/house_enc.csv
  target: price
  # 如需手动指定特征列，取消下一行注释：
  # features: ["area","bedrooms","bathrooms","year_built","location_*"]

split:
  test_size: 0.2
  random_state: 42
  shuffle: true

preprocess:
  impute_num: median        # 数值缺失：mean/median
  scale_num: true           # 数值列是否标准化
  one_hot_cat: true         # 类别是否做独热
  impute_cat: most_frequent # 类别缺失填充：most_frequent/constant

model:
  name: XGBoost
  params:
    n_estimators: 400
    learning_rate: 0.05
    max_depth: 6
    subsample: 0.9
    colsample_bytree: 0.9
    reg_lambda: 1.0
    reg_alpha: 0.0
    tree_method: hist
#    random_state: 42

# ✅ 输出位置与命名（XGBoost/build.py 需要）
outputs:
  base_dir: outputs          # 产物根目录（models/reports/predictions 都放这里）
  tag: xgb_baseline          # 用于命名文件，如 reports/xgb_baseline_metrics.json

# ✅ 评估指标（如 build.py 有用到）
eval:
  metrics: ["MAE","RMSE","R2"]
viz:
  enabled: true        # 需要生成图就 true，不需要可以 false
  dpi: 160
  out_dir: outputs/plots/reg/xgb_baseline
