# 任务配置
task: transfer_diagnosis_dann_raw_signal

# 输入文件 (注意：不再使用features.parquet，而是使用manifest.csv)
manifest_path: "outputs/data/artifacts/manifest.csv"
label_encoder_path: "outputs/models/source_xgb_baseline_label_encoder.pkl"

# 数据处理参数 (供RawSignalDataset使用)
data_params:
  target_fs: 24000
  window_size: 4096
  overlap: 0.5

# DANN 模型与训练参数
model:
  name: "DANN"
  feature_extractor_type: "MHDCNN"

  # --- 关键改动：输入维度现在是信号窗口的长度 ---
  input_dim: 4096

  label_predictor_arch: [64, 32]
  domain_discriminator_arch: [64, 32]

training_params:
  learning_rate: 0.0005
  num_epochs: 100
  batch_size: 64 # 原始信号处理需要更多内存，减小batch size
  adversarial_lambda: 0.5

# 输出配置
outputs:
  base_dir: "outputs"
  tag: "dann_mhdcnn_raw_v1"
  model_path: "outputs/models/dann_mhdcnn_raw_final_model.pth"
  target_predictions_path: "outputs/predictions/DANN/target_preds_dann_mhdcnn_raw.csv"
  visualization_path: "outputs/figs/transfer/tsne_after_dann_mhdcnn_raw.png"