# runs/transfer_dann_2d.yaml

task: transfer_diagnosis_dann_2d
image_manifest_path: "outputs/data/artifacts/image_manifest.csv"
label_encoder_path: "outputs/models/source_xgb_baseline_label_encoder.pkl"

model:
  name: "DANN"
  feature_extractor_type: "CNN2D"
  input_dim: 4096
  input_height: 64
  input_width: 64
  label_predictor_arch: [512, 128]
  domain_discriminator_arch: [128]

training_params:
  # 【修改点3】适当降低学习率，让优化过程更平滑
  learning_rate: 0.0001
  num_epochs: 100
  batch_size: 64

  # 【修改点2】将对抗权重恢复到1.0，因为有MMD辅助
  adversarial_lambda: 1.0

  # 【修改点1】大幅降低MMD权重，使其作为稳定器而非主导力量
  mmd_lambda: 0.1

outputs:
  base_dir: "outputs"
  tag: "dann_dcnn_2d_hybrid_tuned" # 使用新标签以区分实验
  model_path: "outputs/models/dann_hybrid_tuned_final_model.pth"
  target_predictions_path: "outputs/predictions/DANN/target_preds_dann_hybrid_tuned.csv"
  visualization_path: "outputs/figs/transfer/tsne_after_dann_hybrid_tuned.png"