# 任务配置
task: transfer_diagnosis_dann

# 输入文件 (保持不变)
features_path: "outputs/data/artifacts/features.parquet"
label_encoder_path: "outputs/models/source_xgb_baseline_label_encoder.pkl"

# DANN 模型与训练参数 (使用MHDCNN)
model:
  name: "DANN"
  input_dim: 21
  # 注意：我们不再需要 feature_extractor_arch，因为MHDCNN是固定的
  label_predictor_arch: [16] # 特征提取器输出维度变小了，这里可以适当减小
  domain_discriminator_arch: [16]

training_params:
  learning_rate: 0.001 # 对于CNN，可以从稍大的学习率开始尝试
  num_epochs: 200      # 保持足够的训练时间
  batch_size: 128
  adversarial_lambda: 0.2 # MHDCNN特征提取能力更强，可以尝试稍大的lambda来加强领域对齐

# 输出配置 (修改tag以区分实验)
outputs:
  base_dir: "outputs"
  tag: "dann_mhdcnn_v1"
  model_path: "outputs/models/dann_mhdcnn_final_model.pth"
  target_predictions_path: "outputs/predictions/DANN/target_preds_dann_mhdcnn.csv"
  visualization_path: "outputs/figs/transfer/tsne_after_dann_mhdcnn.png"