# src/models/clf/SVM/params.yaml
task: clf
dataset:
  # 【MODIFIED】 Point to the 32kHz feature file
  path: "outputs/data/artifacts/features_32k.parquet"
  target: fault_type
  feature_prefixes: ["td_", "fd_", "env_", "cwt_"]

split:
  n_splits: 5

model:
  name: SVM
  params:
    C: 1.0
    kernel: 'rbf'
    gamma: 'scale'
    probability: true

eval:
  metrics: [ACC, F1, ROC_AUC]

outputs:
  base_dir: outputs
  # 【MODIFIED】 Update the tag for 32kHz experiment outputs
  tag: "svm_baseline_32k"

seed: 42